#!/bin/sh
#
# $Id: tm-html,v 1.4 1997/01/30 02:22:30 steve Exp $
#
# Copyright 1994,1995,1996,1997 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GNU Emacs; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

PATH=${PATH:-/usr/bin:/bin}:`dirname $0 2>/dev/null`; export PATH

if [ "$TM_TMP_DIR" = "" ]; then
    TM_TMP_DIR=/tmp
    export TM_TMP_DIR
fi

if [ "$TM_WWW_BROWSER" = "" ]; then
    TM_WWW_BROWSER=netscape
    export TM_WWW_BROWSER
fi

if [ "$5" = "" ]; then
    filename="$TM_TMP_DIR/mime$$.html"
else
    filename="$TM_TMP_DIR/$5"
fi

echo "$2; $3 -> $filename"

tmdecode "$3" $1 $filename

case "$4" in
"play")
    if [ `echo $TM_WWW_BROWSER | grep netscape` ]; then
	echo netscape
	if [ -h $HOME/.netscape/lock ]; then
	    netscape -remote "openURL(file:$filename,new-window)"
        else
	    netscape $filename
        fi
    else
	echo not netscape
	$TM_WWW_BROWSER $filename
    fi
    trap 'rm -f $filename' 0 1 2 3 13 15
    ;;
"extract")
    echo "extract to $filename"
    ;;
esac
