.TH XEMACS 1 "1997 年 3 月 11 日"
.UC 4
.SH "名前"
xemacs \- 次世代 Emacs
.SH "形式"
.B xemacs
[
.I <コマンド行オプション>
] [
.I <ファイル名>...
]
.br
.\"以下、bold にすべきコマンド名などが英語では italic になっているので、修正。
.SH "機能説明"
.B XEmacs
は、Free Software Foundation の Richard Stallman によって書かれたもので、
.B Emacs 
との互換性を保持したまま多くの改良が加えられたバージョンです。
.B "GNU Emacs "
バージョン 19 の早期リリースをもとに開発され、
.B "GNU Emacs "
の後続リリースと同期がとられています。
.PP
.B XEmacs 
の主なマニュアルは、
.B XEmacs 
サブシステムの 1 つである Info を使ってオンラインで参照することができます。
完成された最新のマニュアルは、そちらを参照してください
(ただし現時点では、Info 形式ドキュメントは英語版のみが用意されています)。
Emacs Lisp 使用方法についての完全なマニュアルとしては
『XEmacs Lisp Programmer's Manual』を、
オンラインで参照することができます。どちらのマニュアルも
.B TeX
書式パッケージを使用すれば、きれいに印刷することができます。
.PP
使用できる
.B XEmacs
の機能は、ほかの
.B Emacs
エディタでできるすべての機能が含まれており、
編集コマンドは Lisp で記述されているため、容易に拡張することができます。
.PP
.B XEmacs
には拡張対話型ヘルプ機能が用意されていますが、この機能を使用するには、
.B XEmacs
ウィンドウとバッファについての扱い方を知っていることが前提となります。
CTRL-h でヘルプ機能を実行します。「XEmacs 自習書(CTRL-h t)」は、
初心者が数分間で
.B XEmacs
の基礎を知ることができる対話型のチュートリアルを呼び出します。
「適切検索...(CTRL-h a)」は、指定した機能を実行するコマンドを
探す手助けをします。
「キー/マウス記述...(CTRL-h k)」は、指定したキー操作の実行内容を表示します。
「関数記述...(CTRL-h f)」は、指定した名前の Lisp 関数を表示します。
さらに「キー/マウス割り当て...(CTRL-h CTRL-k)」を使用すると、
.B XEmacs 
リファレンスマニュアル上のキー操作を参照でき、
「Elisp 関数...(CTRL-h CTRL-f)」を使用すると、
『XEmacs Lisp Programmer's Manual』上の Lisp 関数を参照できます。
ユーザーがウィンドウシステムを使用している場合は、
これらのヘルプ機能はすべてヘルプメニューから使用することができます。
.PP
複数フレーム(トップレベルウィンドウ)、メニューバー、ツールバー、
水平・垂直スクロールバー、ダイアログボックス、拡張マウス機能
などを持つ X のようなウィンドウシステム環境下では、
.B XEmacs
は
拡張 GUI(グラフィカルユーザーインタフェース)をサポートします。
.PP
.B XEmacs 
は、複数のフォントやカラー、可変幅フォント、可変行間隔を
完全にサポートしており、
ピックスマップをバッファに取り込むことも可能です
(これは特に、W3 Web ブラウジングパッケージや一部の
デバッガ、アウトライン機能のインタフェースに用いられます)。
.PP
.B XEmacs 
の「元に戻す」は、バッファに反映された数ステップ前までの変更を
取り消すことができ、編集のミスを簡単に修復することができます。
.PP
.B XEmacs 
には、多くの専用パッケージが用意されています。メールの読み出し (VM、MH-E、
RMail) や発信 (Mail)、ネットニュースの読み出しと投函 (GNUS)、
World Wide Web のブラウズ (W3)、すべての主要なプログラミング言語に
で書かれたソースコードを編集するための特化されたモード、
多くの言語用の構文強調表示 (Font-Lock)、コンパイル (Compile)、
.B XEmacs
ウィンドウ内で動作するサブシェル (Shell)、アウトライン編集 (Outline)、
Lisp の「読み込み、評価、表示」ループの実行 (Lisp-Interaction-Mode)、
ゲーム精神分析医 (Doctor) などです。
.PP
詳細なリファレンスマニュアルはありますが、
他のバージョンの Emacs を使用したことがあれば、
マニュアルなしでも問題なく対応できると思われます。
初めて Emacs を使用する人でも、チュートリアルを学習したり自動
マニュアル機能を利用することで、すぐに基本機能を使うことができるように
なるでしょう。
.PP
.SM "XEmacs オプション"
.PP
XEmacs は、X ウィンドウが動作する環境下では、すべての標準 X ツールキットの
コマンドオプションを認識します。それに加えて、以下のオプションを認識
します
(オプションが一連の複数の処理を意味する場合は、指定された順に実行されます)。
.TP
.BI \-t " デバイス名"
使用中の標準入出力の代わりに、指定されたデバイスを使います。これは
.BR \-nw
オプションを含意しています。
.TP
.BI \-batch
バッチモードで編集を行います。エディタは標準出力にメッセージを送出します。
実行ファイルを指定したり関数を呼び出す場合は、必ず
.BR \-l
、
.BR \-f
、
.B \-eval
オプションを使用してください。
.TP
.B \-nw\ 
ウィンドウシステム特有の表示用コードの使用をすべて禁止します。
現在の TTY を使用します。
.TP
.B \-debug\-init
初期化ファイルの読み込み中にエラーが発生した場合、デバッガを起動します。
.TP
.B \-unmapped
初期フレームをマッピングしません。
.TP
.B \-no\-site\-file
サイト固有の初期化ファイル(site-init.el)を読み込みません。
.TP
.BR \-q "、" \-no\-init\-file
初期化ファイルを読み込みません。
.TP
.BI \-u " ユーザー名、" \-user " ユーザー名"
指定したユーザー固有の初期化ファイルを読み込みます。
.TP
.I ファイル名 
指定したファイルを編集します。
.TP
.BI \+ "行番号"
.I 行番号 
に指定した行に移動します
.br
(+ 符号と行番号の間に空白文字は入れないでください)。
.TP
.BR \-help "、" \-flags "、" \-?
ヘルプメッセージを出力して終了します。
.TP
.BR \-V "、" \-version
バージョン番号を出力して終了します。
.TP
.BI \-f " 関数名、 " \-funcall " 関数名"
.I "関数名 "
に指定した Lisp 関数を実行します。
.TP
.BI \-l " ファイル名、 " \-load " ファイル名"
.I ファイル名
に指定したファイル中の Lisp コードを読み込みます。
.TP
.BI \-eval " フォーム"
.I フォーム
に指定した Lisp のフォームを評価します。
.TP
.BI \-i " ファイル名、" \-insert " ファイル名"
現在のバッファに、
.I ファイル名
に指定したファイルを取り込みます。
.TP
.B \-kill
.B XEmacs
を終了します(
.BR \-batch 
で有効です)。
.PP
.SM "X での XEmacs の使用"
.PP
.B XEmacs
は、X ウィンドウシステム上で正しく動作するように開発されてきました。
X ウィンドウで
.B XEmacs
を起動すると、ディスプレイ内に独自の X ウィンドウを開きます。
ユーザーのオリジナルのウィンドウをそのまま使い続けることができるように、
エディタはバックグラウンドのジョブとして起動したほうがよいでしょう。
.PP
.B XEmacs
は、以下の標準 X オプションを付けて起動することができます。
.TP
.BI \-geometry " ##x##+##+##"
初期ウィンドウのジオメトリを指定します。## には、幅(文字数)、
高さ(文字数)、X オフセット(ピクセル数)、Y オフセット(ピクセル数)
を数字で指定してください。
.I ##x##
や
.I +##+##
などの書式の部分指定も有効です。(ジオメトリ仕様は、標準 X フォーマットに
準拠しています。詳細は
.BR X (1)
を参照してください。)
.TP
.B \-iconic
起動時の初期ウィンドウをアイコンで表示します。
.TP
.BI \-name " プログラム名"
ユーザーの X リソース内にあるデフォルトを参照するために使用される
プログラム名を指定します。
.TP
.BI \-title " タイトル名、" \-T " タイトル名、" \-wn " タイトル名"
.B XEmacs
ウィンドウのタイトル名を指定します。
.TP
.BI \-d " ディスプレイ名、" \-display " ディスプレイ名"
.IR ディスプレイ名
に指定したディスプレイ上に
.B XEmacs
ウィンドウを作成します。
このオプションは、コマンド行で最初 (先頭) に指定してください。
.TP
.BI \-font " フォント名、" \-fn " フォント名"
.B XEmacs
ウィンドウのフォントとして、
.I フォント名
に指定したフォントを使用します。X フォントは 
.B "/usr/lib/X11/fonts"
ディレクトリから選択してください。
.B XEmacs
は、固定幅フォントと可変幅フォントのどちらでも動作しますが、
固定幅フォントを使用することをお勧めします。
.TP
.BI \-scrollbar\-width " ピクセル数"
垂直スクロールバーの幅を指定します。
.TP
.BI \-scrollbar\-height " ピクセル数"
水平スクロールバーの高さを指定します。
.TP
.BI \-bw " ピクセル数、 " \-borderwidth " ピクセル数"
.B XEmacs
ウィンドウの境界幅を指定します。
ウィンドウ両側のデフォルト値は 1 ピクセルです。
.TP
.BI \-ib " ピクセル数、 " \-internal\-border\-width " ピクセル数"
フレームの境界とテキストとの間隔を指定します。
ウィンドウ両側のデフォルト値は 1 ピクセルです。
.TP
.BI \-fg " カラー名、 " \-foreground " カラー名"
テキストの色を設定します。カラー名については、
.B "/usr/lib/X11/rgb.txt"
ファイル中のリストを参照してください。
.TP
.BI \-bg " カラー名、 " \-background " カラー名"
ウィンドウの背景の色を設定します。
.TP
.BI \-bd " カラー名、 " \-bordercolor " カラー名"
ウィンドウ境界の色を設定します。
.TP
.BI \-mc " カラー名"
マウスポインタの色を設定します。
.TP
.BI \-cr " カラー名"
テキストカーソルの色を設定します。
.TP
.BR \-rv "、" \-reverse
前景と背景の色を反転します(反転表示)。
このオプションを使用せずに、
前景色と背景色を明示的に設定することをお勧めします。
.TP
.BI \-xrm " 引数"
コマンド行で任意のリソースを設定することができます。
.B \.Xresource
や
.B \.Xdefaults
ファイル中に指定されるのと同様に、
.I 引数
に指定した値がリソースとして解釈されます。
.PP
ユーザーは、たとえば
.B \.Xresources
や
.B \.Xdefaults
ファイルで、
.B XEmacs 
ウィンドウ用のリソースのデフォルト値を設定することもできます(
.BR xrdb (1)
参照)。
書式は以下のようになります。
.IP
\f3Emacs.\f2キーワード\f3:\f2値\f1
.PP
または
.IP
\f3Emacs*EmacsFrame.\f2キーワード\f3:\f2値\f1
.PP
です (どちらの形式かは、リソースによる)。
.PP
以下の書式を使用して、特定のフレームのリソースを設定することもできます。
.IP
\f3Emacs*\f2フレーム名\f3.\f2キーワード\f3:\f2値\f1
.PP
(VM のような完成されたパッケージは、それらのフレームに固有の
リソース名を与えます。この場合は VM になります。)
.PP
.B XEmacs
では、以下のキーワードに対するデフォルト設定をユーザーが行うことができます。
.TP
.B default.attributeFont (\fPclass\fB Face.AttributeFont)
ウィンドウのテキストフォントを設定します。
.TP
.B default.attributeForeground (\fPclass\fB Face.AttributeForeground)
ウィンドウテキストの色を設定します。
.TP
.B default.attributeBackground (\fPclass\fB Face.AttributeBackground)
ウィンドウの背景色を設定します。
.TP
.B \fIフェイス\fB.attributeFont (\fPclass\fB Face.AttributeFont)
フェイス名のフォントを設定します。
よく使用されるフェイス名を、以下に示します。
.PP
.in +\w'right-margin'u+12n
.ta \w'right-margin'u+4n
.ti -\w'right-margin'u+4n
フェイス		目的
.br
.ti -\w'right-margin'u+4n
default	通常のテキスト。
.br
.ti -\w'right-margin'u+4n
bold	ボールド (太字) テキスト。
.br
.ti -\w'right-margin'u+4n
italic	イタリック (斜体) テキスト。
.br
.ti -\w'right-margin'u+4n
bold-italic	ボールドイタリックテキスト。
.br
.ti -\w'right-margin'u+4n
modeline	モード行テキスト。
.br
.ti -\w'right-margin'u+4n
zmacs-region	マウス選択されたテキスト。
.br
.ti -\w'right-margin'u+4n
highlight	マウス通過時の強調テキスト。
.br
.ti -\w'right-margin'u+4n
left-margin	左マージン内のテキスト。
.br
.ti -\w'right-margin'u+4n
right-margin	右マージン内のテキスト。
.br
.ti -\w'right-margin'u+4n
isearch	検索時の強調テキスト。
.br
.ti -\w'right-margin'u+4n
info-node	Info メニューのテキスト。
.br
.ti -\w'right-margin'u+4n
info-xref	Info 相互参照のテキスト。
.TP
.B \fIフェイス\fB.attributeForeground(\f1class\fB Face.AttributeForeground)
指定フェイス用の前景色を設定します。
.TP
.B \fIフェイス\fB.attributeBackground(\f1class\fB Face.AttributeBackground)
指定フェイス用の背景色を設定します。
.TP
.B \fIフェイス\fB.attributeBackgroundPixmap
.B (\f1class\fB Face.AttributeBackgroundPixmap)\f1
.br
指定フェイス用の背景ピックスマップを設定します。
.TP
.B \fIフェイス\fB.attributeUnderline (\f1class\fB Face.AttributeUnderline)
指定フェイス用の下線の有無を決めます。
.TP
.B reverseVideo (\f1class\fB ReverseVideo)
.IR on 
に設定された場合は、ウィンドウは反転表示します。
このリソースを使用せずに、前景色と背景色を
明示的に設定することをお勧めします。
.TP
.B borderWidth (\fPclass\fB BorderWidth)
ウィンドウの境界幅をピクセル数で設定します。
.TP
.B internalBorderWidth (\fPclass\fB InternalBorderWidth)
ウィンドウの内側境界幅をピクセル数で設定します。
.TP
.B borderColor (\fPclass\fB BorderColor)
ウィンドウ境界の色を設定します。
.TP
.B cursorColor (\fPclass\fB Foreground)
ウィンドウのテキストカーソルの色を設定します。
.TP
.B pointerColor (\fPclass\fB Foreground)
ウィンドウのマウスカーソルの色を設定します。
.TP
.B geometry (\fPclass\fB Geometry)
.B XEmacs
ウィンドウのジオメトリを設定します(上述)。
.TP
.B iconic (\fPclass\fB Iconic)
on に設定されている場合は、
.B XEmacs
ウィンドウは最初にアイコン化されて表示されます。
.TP
.B menubar (\fPclass\fB Menubar)
.B XEmacs
ウィンドウにメニューバーを表示させるかどうかを設定します。初期値は true です。
.TP
.B initiallyUnmapped (\fPclass\fB InitiallyUnmapped)
.B XEmacs
が起動時にアンマップされた初期フレームを残すかどうかを設定します。
.TP
.B barCursor (\fPclass\fB BarCursor)
カーソルの形状を、箱型またはバーに設定します。
.TP
.B title (\fPclass\fB Title)
.B XEmacs
ウィンドウのタイトル名を設定します。
.TP
.B iconName (\fPclass\fB Title)
.B XEmacs
ウィンドウアイコンの名前を設定します。
.TP
.B scrollBarWidth (\fPclass\fB ScrollBarWidth)
垂直スクロールバーの幅をピクセル数で設定します。
値を 0 にすると、垂直スクロールバーは表示されません。
.TP
.B scrollBarHeight (\fPclass\fB ScrollBarHeight)
水平スクロールバーの高さをピクセル数で設定します。
値を 0 にすると、水平スクロールバーは表示されません。
.TP
.B scrollBarPlacement (\fPclass\fB ScrollBarPlacement)
垂直・水平スクロールバーの位置を設定します。"top-left"、"bottom-left"、 
"top-right"、"bottom-right"のいずれかを選択します。
デフォルトでは、Motif と Lucid 用には "bottom-right" が、
Athena 用には "buttom-left" が設定されています。
.TP
.B topToolBarHeight (\fPclass\fB TopToolBarHeight)
上部のツールバーの高さをピクセル数で設定します。
値を 0 にすると、ツールバーは表示されません。
.TP
.B bottomToolBarHeight (\fPclass\fB BottomToolBarHeight)
下部ツールバー の高さをピクセル数で設定します。
値を 0 にすると、下部ツールバーは表示されません。
.TP
.B leftToolBarWidth (\fPclass\fB LeftToolBarWidth)
左側のツールバーの幅をピクセル数で設定します。
値を 0 にすると、左側のツールバーは表示されません。
.TP
.B rightToolBarWidth (\fPclass\fB RightToolBarWidth)
右側のツールバーの幅をピクセル数で設定します。
値を 0 にすると、右側のツールバーは表示されません。
.TP
.B topToolBarShadowColor (\fPclass\fB TopToolBarShadowColor)
ツールバーの上部シャドウの色を設定します。
(すべてのツールバーに有効。上部ツールバー以外にも有効です。)
.TP
.B bottomToolBarShadowColor (\fPclass\fB BottomToolBarShadowColor)
ツールバーの下部シャドウの色を設定します。
(すべてのツールバーに有効。上部ツールバー以外にも有効です。)
.TP
.B topToolBarShadowPixmap (\fPclass\fB TopToolBarShadowPixmap)
ツールバーの上部シャドウのピックスマップを設定します。
(すべてのツールバーに有効。上部ツールバー以外にも有効です。)
設定されていれば、このリソースは対応するカラーリソースを無効にします。
.TP
.B bottomToolBarShadowPixmap (\fPclass\fB BottomToolBarShadowPixmap)
ツールバーの下部シャドウのピックスマップを設定します。
(すべてのツールバーに有効。上部ツールバー以外にも有効です。)
設定されていれば、このリソースは対応するカラーリソースを無効にします。
.TP
.B toolBarShadowThickness (\fPclass\fB ToolBarShadowThickness)
ツールバーを囲むシャドウ濃度をピクセル数で設定します。
.TP
.B visualBell (\fPclass\fB VisualBell)
スクリーン点滅またはビープ音のどちらを使用するかを設定します。
.TP
.B bellVolume (\fPclass\fB BellVolume)
ビープ音の音量を設定します。設定範囲は 0 から 100 です。
.TP
.B useBackingStore (\fPclass\fB UseBackingStore)
.B XEmacs
X ウィンドウのバッキングストア属性を設定するかどうかを決定します。
この属性を設定すると、
X サーバーが使用するメモリーが多くなりますが、
スクリーンを更新する際の X トラフィックが少なくなります。
また、モデム接続のような低速回線を使った
.I X
サーバーとの接続に有効です。
.TP
.B textPointer (\fPclass\fB Cursor)
テキスト上にマウスがあるときに使用するカーソルを設定します。
.TP
.B selectionPointer (\fPclass\fB Cursor)
マウス選択されたテキスト範囲上にマウスがあるときに使用する
カーソルを設定します。
.TP
.B spacePointer (\fPclass\fB Cursor)
バッファ内の空白スペース上にマウスがあるときに(つまり、
行末やファイルの最後で) 使用するカーソルを設定します。
.TP
.B modeLinePointer (\fPclass\fB Cursor)
モードライン上にマウスがあるときに使用するカーソルを設定します。
.TP
.B gcPointer (\fPclass\fB Cursor)
ガーベッジコレクション中に表示するカーソルを設定します。
.TP
.B scrollbarPointer (\fPclass\fB Cursor)
スクロールバー上にマウスがあるときに使用するカーソルを設定します。
.TP
.B pointerColor (\fPclass\fB Foreground)
マウスカーソルの前景色を設定します。
.TP
.B pointerBackground (\fPclass\fB Background)
マウスカーソルの背景色を設定します。
.PP
.SM "マウスの使用"
.PP
以下のリストは、X11 における
.B XEmacs
ウィンドウでの、マウスボタンの割り当てです。

.in +\w'CTRL-SHIFT-middle'u+4n
.ta \w'CTRL-SHIFT-middle'u+4n
.ti -\w'CTRL-SHIFT-middle'u+4n
マウスボタン       機能
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
左                 ポイントの位置決めと、テキストの選択。
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
中央               テキストのペースト。
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
右                 オプションメニューのポップアップ
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
SHIFT-左           選択範囲の拡張。
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
CTRL-左            選択した内容をポイント位置に挿入。
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
CTRL-中央          ポイントの位置決めとその位置でのテキストの選択。
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
CTRL-SHIFT-左      選択した内容を削除しその内容をポイント位置に挿入。
.br
.ti -\w'CTRL-SHIFT-middle'u+4n
META-左            箱型選択。
.SH "ファイル"
.LP
Lisp コードが、起動時にユーザーの初期化ファイル \fB$HOME/.emacs\fP から
読み込まれます。
.LP
\f3/usr/local/info\f1
.br
Info 文書ブラウザ
(
.BR XEmacs 
のサブシステム)の参照するファイル。
『XEmacs Reference Manual』と『XEmacs Lisp Programmer's Manual』
の完全なテキストが、所定の階層構造で収められています。
.LP
\f3/usr/local/lib/xemacs-$VERSION/info\f1
.br
Info ファイル(この位置とはかぎらない)
.LP
\f3/usr/local/lib/xemacs-$VERSION/src\f1
.br
C ソースファイルとオブジェクトファイル(存在しない場合もある)
.LP
\f3/usr/local/lib/xemacs-$VERSION/lisp/*\f1
.br
多くの編集コマンドを定義する Lisp ソースファイルとコンパイル済みファイル。
これらのファイルは機能や個々のパッケージ別にサブディレクトリ内に
分類され、置かれています。いくつかのファイルは
前もって読み込まれています。それ以外のものは、使用時にこれらのディレクトリから、
自動的に読み込まれます。
.LP 
\f3/usr/local/lib/xemacs-$VERSION/etc\f1
.br
いくつかの情報ファイル、ピックスマップファイル、
パッケージに使用されるデータファイルなど。
.LP
\f3/usr/local/lib/xemacs-$VERSION/$CONFIGURATION\f1
.br
XEmacs に使用されるさまざまなプログラムファイル。
.LP
\f3/usr/local/lib/xemacs-$VERSION/$CONFIGURATION/DOC\f1
.br
Lisp プリミティブ (基本関数) と \fBXEmacs\fP にあらかじめ
読み込まれた Lisp 関数のドキュメント文字列。
これらのファイルは、\fBXEmacs\fP 本体のサイズを減らすためにここに保管
されています。
.LP
\f3/usr/local/lib/xemacs-$VERSION/etc/SERVICE\f1
.br
\fBXEmacs\fP ユーザーのための、学習、保守、移植、
カスタマイズなどのさまざまなサービスを提供する人々についてまとめています。
.LP
\f3/usr/local/lib/xemacs/lock\f1
.br
2 人のユーザーが 1 つのファイルを同時に更新できないように、
.BR XEmacs
で更新中のすべてのファイルに対してできるロックファイルを保持します。
.LP
\f3/usr/local/lib/xemacs/site-lisp\f1
.br
ローカルに作成する Lisp ファイル。
.LP
\f3/usr/lib/X11/rgb.txt\f1
.br
正式の X カラー名がリストされています。
.PP
.SH "使用上の留意点と問い合わせ先"
.B XEmacs
に関するバグや修正の報告先として、また助言を求める宛先として、
comp.emacs.xemacs ニュースグループがあります。
ただし、問題点をバグとして報告する前に、
本当にそれがバグであるか、誤解や意図的な機能ではないか
ということをお確かめください。バグレポートの方法や時期については、
リファレンスマニュアル(または Into システム) の後半近くある
「Reporting XEmacs Bugs」という章をお読みください。
また、報告するバグレポートには、動作中の
.B XEmacs
のバージョン番号とそれが動作しているシステムを記入してください。
最後に、バグの原因とそれが発生した状況を、できるだけそのまま保存しておいて
ください。その保存状態が良ければ簡単に修正できる可能性が高くなります。
できるだけご協力をお願いします。

このニュースグループは、xemacs@xemacs.org というメールリストからの発信、受信を
双方向に行うことができます。ネットニュースに簡単にアクセスできないような場合は、
newsgroup に代わってメールリストを読むことができます。メールリストへの追加
ご希望の方は、xemacs-request@xemacs.org へメールをお送りください。
(直接リストにメールを送信しないでください。)

.B XEmacs
の保守担当者は、定期的にニュースグループを読んでいます。そして報告された
バグに対して迅速に修正をするように努めています。しかしながら、すべての
メッセージが保守担当者から返答を受けることができるわけではありません。
保守担当者以外に多数の人達がニュースグループを読んでおり、通常彼らからも
出くわした問題を解決するための助言を得ることができます。

ニュースグループから得られる情報以上に、詳細なサポートが必要な場合は、
SERVICE ファイル(上述)を参照してください。
そのファイルに、担当者がリストされています。

XEmacs のメールリストについての詳細は、
.B /usr/local/lib/xemacs-$VERSION/etc/MAILINGLISTS
のファイルを参照してください。
.SH "非制約事項"
.PP
.B XEmacs
は、フリーのソフトウェアです。
.B XEmacs 
General Public License に述べられている限りにおいて、だれでも
.B XEmacs 
やそれに付随したもののコピー、およびリファレンスマニュアルに表示されている
内容のコピーを、任意の人に提供することが許されています。
.PP
.B XEmacs
は、UNIX システムの配布物とともにパッケージされて提供されることがありますが、
.B XEmacs
は常にそれらのシステムに関するライセンスの範囲外です。もし
.B XEmacs 
もそのライセンスに含まれているとすれば、それは配布許可要項に反します。
いかなる人も
.B XEmacs 
の配布に関しては何の制約も受けてはならない、というのが 
General Public License の本来の目的です。
.SH "関連項目"
.BR X (1),
.BR xlsfonts (1),
.BR xterm (1),
.BR xrdb (1), 
.BR emacs (1), 
.BR vi (1)
.SH "著者"
.PP
.B XEmacs 
は、Chuck Thompson <cthomp@xemacs.org>、Ben Wing <ben@xemacs.org>、
Jamie Zawinski <jwz@netscape.com>、Richard Mlynarik <mly@adoc.xerox.com>、
Martin Buchholz <mrb@eng.sun.com> 他、によって書かれました。
Free Software Foundation の Richard Stallman の書いた 
.B "GNU Emacs "
バージョン 
.I 19 
の早期バージョンをもとにしていましたが、
.B GNU Emacs 
が使用可能となった後では、その後続リリースに同期されています。
もともとは、(今や存在しない) Lucid, Inc. によって書かれたもので、
.B "Lucid Emacs "
と呼ばれていました。
.PP
Chuck Thompson が
.B XEmacs
の再表示の基本部分を書き、
.B XEmacs
の FTP と WWW サイトを保持し、
バージョン 19.11 (
.B XEmacs 
とよばれた最初のリリース) からすべての
.B XEmacs 
の機能がリリースされました。
Ben Wing は、アジア言語のサポート、オンラインマニュアル (マニュアル
ページと多くの FAQ を含む)、外部ウィジェットコードを書き、低レベルだった
.B XEmacs 
サブシステムの多くの基本部分を強化し、書き直しました。
Jamie Zawinski は、
.B "Lucid Emacs "
の初期バージョン (19.0) から最終バージョン (19.10) までのすべてを
リリースし、これらすべてのリリースの主コード貢献者でした。
Richard Mlynarik は、
.B XEmacs 
Lisp オブジェクト割り当てシステムを書き直しと、キーマップコードと
ミニバッファコードの修正、そして
.B XEmacs 
と
.B GNU Emacs 
バージョン
.IR 19 
の初期の同期を行いました。
.PP
その他多くの人も、多大な貢献を続けてきました。詳細な内容(別の観点
から見た \fBXEmacs\fP の長い歴史や鮮明な画像、\fBXEmacs\fP 貢献者たち
の人物紹介など)については、
ヘルプメニューの「XEmacs について」を参照してください。
.SH "追加情報"
\fBXEmacs\fP の追加情報については、
ヘルプメニューの「XEmacs について」(上述)を参照するか、
.B /usr/local/lib/xemacs-$VERSION/etc/NEWS
ファイルをお読みください。または Web ブラウザで
.PP
http://www.xemacs.org/
.PP
を指定してすると、\fBXEmacs\fP についての最新情報が得られます。
.PP
.B XEmacs
についての FAQ (よく尋ねられる質問) も、この URL で見つけることができます。
\fBXEmacs\fP 内の Info システムからは、使用可能な旧バージョンに
アクセスすることも可能です。
.PP
最新バージョンの \fBXEmacs\fP は、
.B "ftp://ftp.xemacs.org/pub/xemacs/"
またはお近くのミラーサイトから匿名 (anonymous) FTP で
ダウンロードすることができます。
以下にミラーサイトの一覧を記述します。
ただし、ミラーサイトが変更されてアクセスできない場合もあります。
.PP
ftp://ftp.ai.mit.edu/pub/xemacs/
.br
ftp://ftp.uu.net/systems/gnu/xemacs/
.br
ftp://ftp.sunet.se/pub/gnu/xemacs/
.br
ftp://ftp.cenatls.cena.dgac.fr/pub/Emacs/xemacs/
.br
ftp://liasun3.epfl.ch/pub/gnu/xemacs/
.br
ftp://ftp.th-darmstadt.de/pub/editors/xemacs/
.br
ftp://audrey.levels.unisa.edu.au/xemacs/
.br
ftp://sunsite.doc.ic.ac.uk/gnu/xemacs/
.br
ftp://ftp.ibp.fr/pub/emacs/xemacs/
.br
ftp://uiarchive.cso.uiuc.edu/pub/packages/xemacs/
.br
ftp://ftp.technion.ac.il/pub/unsupported/gnu/xemacs/
.br
ftp://thphys.irb.hr/pub/xemacs/
.PP
ミラーサイトの最新リストについては、Web サイトをご覧ください。

